### ISSUE TITLE
Chamada a função inexistente no PHP 7

### ISSUE THREAD

**Issue by danielcoelhocgu** [supergovbr/mod-sei-protocolo-integrado#22]
**Descreva o erro**
Ao executar o agendamento ProtocoloIntegradoAgendamentoRN::publicarProtocoloIntegrado, ocorre o erro "Call to undefined function ereg_replace() in /opt/v400/sei/web/modulos/protocolo-integrado/rn/ProtocoloIntegradoMonitoramentoProcessosRN.php:1004".

Segue a linha que dá erro:
https://github.com/supergovbr/mod-sei-protocolo-integrado/blob/64f13ccaee95c005c065c24f2a679e7225954bb7/src/rn/ProtocoloIntegradoMonitoramentoProcessosRN.php#L1004

Pelo que pesquisei a função `ereg_replace` foi removida no PHP 7, que é a versão do nosso ambiente. Ela deve ser substituída por `preg_replace`.

-----

**Para reproduzir**
Execute o agendamento ProtocoloIntegradoAgendamentoRN::publicarProtocoloIntegrado, seja de forma manual ou automática, em um ambiente do SUPER com PHP 7 ou superior.

-----

**Comportamento esperado**
Agendamento ser executado sem falhas.

-----

**Contexto da falha (Por favor, complete a seguinte informação):**
 - Versão do sistema: Módulo 3.0.0  / SUPER 4.0.3.5
 - Navegador: Firefox
 - Perfil do Usuário: administrador
 - Banco de Dados: SQL Server

-----
**Log de Erros**
```
Erro: Error: Call to undefined function ereg_replace() in /opt/v400/sei/web/modulos/protocolo-integrado/rn/ProtocoloIntegradoMonitoramentoProcessosRN.php:1004
Stack trace:
#0 /opt/v400/sei/web/modulos/protocolo-integrado/rn/ProtocoloIntegradoMonitoramentoProcessosRN.php(980): ProtocoloIntegradoMonitoramentoProcessosRN->validarCPF('02798408105')
#1 /opt/v400/sei/web/modulos/protocolo-integrado/rn/ProtocoloIntegradoMonitoramentoProcessosRN.php(794): ProtocoloIntegradoMonitoramentoProcessosRN->gerarNomeInteressadoComCpfEscondido('VINICIUS RAFAEL...')
#2 /opt/v400/sei/web/modulos/protocolo-integrado/rn/ProtocoloIntegradoMonitoramentoProcessosRN.php(132): ProtocoloIntegradoMonitoramentoProcessosRN->publicarProcessosMonitorados(Array)
#3 /opt/v400/infra/infra_php/InfraRN.php(140): ProtocoloIntegradoMonitoramentoProcessosRN->publicarProcessosConectado(Object(ProtocoloIntegradoParametrosDTO))
#4 /opt/v400/sei/web/modulos/protocolo-integrado/rn/ProtocoloIntegradoAgendamentoRN.php(32): InfraRN->__call('publicarProcess...', Array)
#5 /opt/v400/infra/infra_php/formularios/rn/InfraAgendamentoTarefaRN.php(621): ProtocoloIntegradoAgendamentoRN->publicarProtocoloIntegrado(Array)
#6 /opt/v400/infra/infra_php/formularios/infra_agendamento_tarefa_lista.php(38): InfraAgendamentoTarefaRN->executar(Object(InfraAgendamentoTarefaDTO))
#7 /opt/v400/infra/infra_php/InfraControlador.php(104): require_once('/opt/v400/infra...')
#8 /opt/v400/sei/web/controlador.php(1703): InfraControlador::processar('infra_agendamen...', Object(PaginaSEI), Object(SessaoSEI), Object(BancoSEI), Object(LogSEI), Object(CacheSEI), Object(AuditoriaSEI))
#9 {main}
Detalhes:

Trilha de Processamento:
#0 /opt/v400/sei/web/modulos/protocolo-integrado/rn/ProtocoloIntegradoMonitoramentoProcessosRN.php(980): ProtocoloIntegradoMonitoramentoProcessosRN->validarCPF('02798408105')
#1 /opt/v400/sei/web/modulos/protocolo-integrado/rn/ProtocoloIntegradoMonitoramentoProcessosRN.php(794): ProtocoloIntegradoMonitoramentoProcessosRN->gerarNomeInteressadoComCpfEscondido('VINICIUS RAFAEL...')
#2 /opt/v400/sei/web/modulos/protocolo-integrado/rn/ProtocoloIntegradoMonitoramentoProcessosRN.php(132): ProtocoloIntegradoMonitoramentoProcessosRN->publicarProcessosMonitorados(Array)
#3 /opt/v400/infra/infra_php/InfraRN.php(140): ProtocoloIntegradoMonitoramentoProcessosRN->publicarProcessosConectado(Object(ProtocoloIntegradoParametrosDTO))
#4 /opt/v400/sei/web/modulos/protocolo-integrado/rn/ProtocoloIntegradoAgendamentoRN.php(32): InfraRN->__call('publicarProcess...', Array)
#5 /opt/v400/infra/infra_php/formularios/rn/InfraAgendamentoTarefaRN.php(621): ProtocoloIntegradoAgendamentoRN->publicarProtocoloIntegrado(Array)
#6 /opt/v400/infra/infra_php/formularios/infra_agendamento_tarefa_lista.php(38): InfraAgendamentoTarefaRN->executar(Object(InfraAgendamentoTarefaDTO))
#7 /opt/v400/infra/infra_php/InfraControlador.php(104): require_once('/opt/v400/infra...')
#8 /opt/v400/sei/web/controlador.php(1703): InfraControlador::processar('infra_agendamen...', Object(PaginaSEI), Object(SessaoSEI), Object(BancoSEI), Object(LogSEI), Object(CacheSEI), Object(AuditoriaSEI))
#9 {main}
```

**Comment by danielcoelhocgu** [comment]
Criado PR #23 para corrigir o problema.

**Comment by caduvieira** [comment]
Adicionado pelo commit #[5296ebb](https://github.com/supergovbr/mod-sei-protocolo-integrado/commit/5296ebbaeb452960d9f80e1f0531a4fe332b2295)
